#pragma once

#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 600

#define BOARD_HEIGHT 31
#define BOARD_WIDTH 28

#define TILE_HEIGHT 16
#define TILE_WIDTH 16
#define TILE_SIZE 16

#define BOARD_CENTER_OFFSET_X WINDOW_WIDTH / 2 - (TILE_WIDTH * BOARD_WIDTH) / 2
#define BOARD_CENTER_OFFSET_Y WINDOW_HEIGHT / 2 - (TILE_HEIGHT * BOARD_HEIGHT) / 2

#define SCREEN_FPS 30